version: "3" 

services:

  # ui:
  #   image: ui
  #   stdin_open: true 
  #   tty: true 
  #   build:
  #     context: frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4003:4003"
  #   volumes:
  #     - "./frontend:/app"

  api: 
    image: api
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "4004:4004"
    volumes:
      - "./backend:/app"
    env_file:
      - "backend/.env"

volumes:
  db:
    driver: local
  api: 
