version: "3.8" 

services:
  api: 
    image: api
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/app"
    env_file:
      - "backend/.env"
    depends_on: 
      - db
volumes:
  db:
    driver: local
  api: 
